projects:
  app:
    schemaPath: './src/schema.graphql'
    extensions:
      endpoints:
        default: 'http://localhost:4444/graphql'
  prisma:
    schemaPath: 'src/generated/prisma-client/prisma.graphql'
    extensions:
      prisma: prisma.yml
